version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  migrate:
    build:
      context: .
      dockerfile: docker/migrate.Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'db'
      MIGRATIONS_DIRECTORY: 'migrations'
  palindrome:
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: docker/palindrome.Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'db'
      PORT: '3000'
      GO_ENV: 'production'
  tests:
    build:
      context: .
      dockerfile: docker/tests.Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST: 'db'
      PORT: '3000'
      GO_ENV: 'production'
      API_HOST: 'palindrome'
      API_PORT: '3000'
